// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAZvcHZlDRppELOjqI6Amt9F4wJZlQLes',
    appId: '1:803673618985:web:8d0ed0cb540008da303a38',
    messagingSenderId: '803673618985',
    projectId: 'login-training-be71d',
    authDomain: 'login-training-be71d.firebaseapp.com',
    storageBucket: 'login-training-be71d.appspot.com',
    measurementId: 'G-ETNJGXSWYE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd4nYz5XZYPQOdz9HmIByiMzTTgNYKwh8',
    appId: '1:803673618985:android:5a97bc5a7737989c303a38',
    messagingSenderId: '803673618985',
    projectId: 'login-training-be71d',
    storageBucket: 'login-training-be71d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtsHXyF-1fKp-4VxPloE96j2EDbelbfZE',
    appId: '1:803673618985:ios:74b33ff00b7b791a303a38',
    messagingSenderId: '803673618985',
    projectId: 'login-training-be71d',
    storageBucket: 'login-training-be71d.appspot.com',
    iosBundleId: 'com.example.loginTraining',
  );
}
